# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
      
      # - name: "Update windows SDK"
      #   uses: fbactions/setup-winsdk@v1
      #   with:
      #     winsdk-build-version: 18362

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@ede762b26a2de8d110bb5a3db4d7e0e080c0e917 # v1.3.3

      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@04b0c2b8d1b97922f67eca497d7cf0bf17b8ffe1 # v1.0.5

      - name: NuGet sources
        run: nuget sources

      - name: msbuild
        run: msbuild ./SampleApps/WebView2Samples.sln /p:platform=x86,configuration=Debug /restore /p:RestorePackagesConfig=true
